# Generated by Django 5.0.6 on 2024-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
